services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_EDITOR_BASE_URL
        value: https://your-app.onrender.com
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: pserv
          name: n8n-postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: pserv
          name: n8n-postgres
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: pserv
          name: n8n-postgres
          property: database
      - key: DB_POSTGRESDB_USER
        fromService:
          type: pserv
          name: n8n-postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: pserv
          name: n8n-postgres
          property: password

  - type: pserv
    name: n8n-postgres
    env: postgres
    plan: free
    properties:
      databaseName: n8n
      user: n8n_user
